runtime: python39  # Python 3.9
entrypoint: uvicorn app:app --host=0.0.0.0 --port=$PORT

env_variables:
  EE_PROJECT_ID: "ee-hanzilabinyounasai"
  OLLAMA_BASE_URL: "http://localhost:11434"  # This needs special handling (see notes below)
  OLLAMA_MODEL: "gemma2:2b"
  SECRET_KEY: "your-secret-key-keep-it-safe"

handlers:
- url: /.*
  script: auto