version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - geogemma-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./ee_config/credentials:/root/.config/earthengine/credentials:ro
    environment:
      - EE_PROJECT_ID=${EE_PROJECT_ID}
      - SECRET_KEY=${SECRET_KEY:-default_secret_key_for_dev}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
    # Remove GOOGLE_APPLICATION_CREDENTIALS for OAuth user credentials
    # - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
    depends_on:
      - ollama
    networks:
      - geogemma-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - geogemma-network
    restart: unless-stopped

networks:
  geogemma-network:
    driver: bridge

volumes:
  ollama_data: