version: '3.8'

services:
  # Main GIS AI Agent Application
  gis-agent:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - gis_data:/app/data
      - gis_logs:/app/logs
    networks:
      - gis-network
    # Don't expose the port to the host, only to the nginx service
    depends_on:
      - redis

  # Nginx reverse proxy for security
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    networks:
      - gis-network
    depends_on:
      - gis-agent

  # Redis for caching and rate limiting
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - gis-network

volumes:
  gis_data:
    driver: local
  gis_logs:
    driver: local
  redis_data:
    driver: local

networks:
  gis-network:
    driver: bridge 